hw03: mystruct.h File Reference
mystruct.h File Reference
Data Structures
struct Employee
Macros
#define MYSTRUCT_H
#define ARRAY_SIZE (10)
#define STRING_LENGTH (6)
Functions
Employee * make_employee (char *id, int birth_year, int start_year)
void get_id (Employee *c)
char * string_make (int length)
char random_gen ()
Employee * struct_rand ()
Employee ** array_struct (int structs)
void print_array_structs (Employee **arr, int size)
Employee ** shallow_copy (Employee **arr, int num_of_employees)
Employee ** deep_copy (Employee **arr, int num_of_employees)
void free_array_employees (Employee **arr, int num_of_employees)
Macro Definition Documentation
ARRAY_SIZE
#define ARRAY_SIZE (10)
MYSTRUCT_H
#define MYSTRUCT_H
mystruct.h
Author
Preet Patel My own versions of some of employee pointer and random string functions
STRING_LENGTH
#define STRING_LENGTH (6)
Function Documentation
array_struct()
Employee** array_struct (int structs)
References STRING_LENGTH, and struct_rand().
Referenced by main().
deep_copy()
Employee** deep_copy (Employee ** arr, int num_of_employees)
References make_employee().
Referenced by main().
free_array_employees()
void free_array_employees (Employee ** arr, int num_of_employees)
Referenced by main().
get_id()
void get_id (Employee * c)
References Employee::id.
Referenced by main().
make_employee()
Employee* make_employee (char * id, int birth_year, int start_year)
mystruct.c
Author
Preet Patel Functions with struct pointers and arrays of struct pointers.
@make_employee, makes an employee with inputted data
Parameters
char *id, id of employee
int birth_year, holds birth year of employee
int start_year, holds start year of employee
Returns
employee pointer to newly created employee
@get_id, prints id of an employee
Parameters
Employee* c, an employee struct
Returns
void, print statement to console of id of inputted employeee
@random_gen, generates a random character in range (A-Z, a-z, 0-9)
Returns
random character generated
@string_make, makes a string of random characters of specified length
Parameters
int length, length of string to be made, set with symbolic constant
Returns
char pointer to random string made
@struct_rand, makes employee with random data
Returns
Employee pointer to newly made random employee
@array_struct, creates an array of random struct pointers
Parameters
int employees, number of employees to be put in array
Returns
employee pointer that points to an array of employee pointers
@print_array_structs, prints employees in array
Parameters
Employee** arr, takes an employee pointer pointing to an array of employee pointers
int size, number of employee pointers in array
Returns
prints employees to console
@shallow_copy, creates a shallow copy
Parameters
Employee** arr, takes an employee pointer pointing to an array of employee pointers
int num_of_employees, number of employee pointers in array
Returns
new shallow copy
@deep_copy, creates a deep copy
Parameters
Employee** arr, takes an employee pointer pointing to an array of employee pointers
int num_of_employees, number of employee pointers in array
Returns
new deep copy
@free_array_employees, frees memory allocated to array of employee pointers
Parameters
Employee** arr, takes an employee pointer pointing to an array of employee pointers
int num_of_employees, number of employee pointers in array
Returns
void
References ARRAY_SIZE.
Referenced by deep_copy(), main(), and struct_rand().
print_array_structs()
void print_array_structs (Employee ** arr, int size)
Referenced by main().
random_gen()
char random_gen ()
Referenced by string_make().
shallow_copy()
Employee** shallow_copy (Employee ** arr, int num_of_employees)
Referenced by main().
string_make()
char* string_make (int length)
References random_gen().
Referenced by struct_rand().
struct_rand()
Employee* struct_rand ()
References make_employee(), STRING_LENGTH, and string_make().
Referenced by array_struct(), and main().