hw03: stest.c File Reference
stest.c File Reference
#include "mystruct.h"
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
Functions
int main (int argc, const char *argv[])
Function Documentation
main()
int main (int argc, const char * argv[])
stest.c Program to demonstrate character arrays and dynamically-allocated memory.
Author
Preet Patel @main, demonstrates functions of employee pointers and random string generators.
Parameters
int argc, number of commands on command line
const *char argv[], array of command on command line
Returns
, int indicating success or failure
@memory_management, frees any memory no longer needed and allocated from functions using malloc
References ARRAY_SIZE, array_struct(), Employee::birth_year, deep_copy(), free_array_employees(), get_id(), make_employee(), print_array_structs(), shallow_copy(), Employee::start_year, and struct_rand().